name: 'Weather'
description: 'Retrieve the current weather data'
inputs:
  location:
    description: "Id of the location"
    required: true
  api-key:
    description: "API Key"
    required: true
outputs:
  sunrise:
    description: 'Sun set displayed in ISO8601 format.'
  sunset:
    description: 'Sun rise displayed in ISO8601 format.'
  icon:
    description: 'Numeric value representing an icon that matches the forecast.'
  iconPhrase:
    description: 'Phrase description of the icon.'
  cloudCover:
    description: 'Percent representing cloud cover.'
  moonPhase:
    description: 'Moon phase.'
  moonRise:
    description: 'Moon rise displayed in ISO8601 format.'
  moonSet:
    description: 'Moon set displayed in ISO8601 format.'
runs:
  using: 'node12'
  main: 'index.js'
