name: 'Write Property'
description: 'Writes and commits a property'
inputs:
  key:
    description: "Key of the property to write"
    required: true
  value:
    description: "Value of the property to write"
    required: true
runs:
  using: 'node12'
  main: 'index.js'
