name: post-comment

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'Author of the commentor'
        required: true
      body:
        description: 'Body of the comment'
        required: true
      url:
        description: 'Url of the commenter'
        required: true
      discussionId:
        description: 'ID of the discussion'
        required: true

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 
        if: always()
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: post_discussion_comment
        with:
          query: |
            mutation addDiscussionComment($discussion: ID!, $body: String!) {
              addDiscussionComment(input: {discussionId: $discussion, body: $body}) {
                comment {
                  id
                }
              }
            }
          discussion: "'${{github.event.inputs.discussionId}}'"
          body: |
            ---
            author: ${{github.event.inputs.author}}
            url: ${{github.event.inputs.url}}
            ---
            ${{github.event.inputs.body}}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

