name: Virtual Town Daylight Hours

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]


jobs:
  fetch-daylight-hours:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - name: get daylight hours
        id: daylight
        uses: ./.github/actions/daylight
        with:
          location: 331470
          api-key: ${{ secrets.ACCU_WEATHER_API_KEY }}
      - name: write sunrise 
        id: write-sunrise
        uses: ./.github/actions/write-property
        with:
          key: 'sunrise'
          value: ${{ steps.daylight.outputs.sunrise }}
          token: ${{ secrets.VIRTUAL_TOWN_MAYORAL_TOKEN }}
      - name: write sunset 
        id: write-sunset
        uses: ./.github/actions/write-property
        with:
          key: 'sunset'
          value: ${{ steps.daylight.outputs.sunset }}
          token: ${{ secrets.VIRTUAL_TOWN_MAYORAL_TOKEN }}

