name: Virtual Town Daylight Hours

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]


jobs:
  fetch-daylight-hours:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm ci

      - name: get daylight hours
        id: daylight
        uses: ./.github/actions/daylight
        with:
          location: 331470
          api-key: ${{ secrets.ACCU_WEATHER_API_KEY }}

      - name: write sunrise 
        id: write-sunrise
        uses: ./.github/actions/write-property
        with:
          key: 'sunrise'
          value: ${{ steps.daylight.outputs.sunrise }}

      - name: write sunset 
        id: write-sunset
        uses: ./.github/actions/write-property
        with:
          key: 'sunset'
          value: ${{ steps.daylight.outputs.sunset }}

      - name: write icon 
        id: write-icon
        uses: ./.github/actions/write-property
        with:
          key: 'icon'
          value: ${{ steps.daylight.outputs.icon }}

      - name: write icon_phrase 
        id: write-icon-phrase
        uses: ./.github/actions/write-property
        with:
          key: 'icon_phrase'
          value: ${{ steps.daylight.outputs.icon_phrase }}

      - name: build
        run: npm run build -- --prefix-paths

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

